source 'https://rubygems.org'

gem 'rails', '4.1.2'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'puma', '~> 2.8.2'
gem 'sidekiq', '~> 3.1.2'
gem 'sinatra', '>= 1.4.5', require: false